Repository NikolaVetnic/Timelines, pull requests merged in 2024-12, with the labels that each got.

#2 Create a "Getting Started" Page in the Docs Vault and the Backend Solution Readme
  Backend/.obsidian/app.json
  Backend/.obsidian/appearance.json
  Backend/.obsidian/core-plugins.json
  Backend/.obsidian/workspace.json
  Backend/README.md
Labels: documentation

#6 Create the Timelines, Notes, Reminders and Files Modules
  Backend/src/Applications/Core/Core.Api/Core.Api.csproj
  Backend/src/Applications/Core/Core.Api/Program.cs
  Backend/src/Modules/Files/Files.Api/Extensions/ServiceCollectionExtensions.cs
  Backend/src/Modules/Files/Files.Api/Files.Api.csproj
  Backend/src/Modules/Files/Files.Application/Files.Application.csproj
  Backend/src/Modules/Files/Files.Domain/Files.Domain.csproj
  Backend/src/Modules/Files/Files.Infrastructure/Files.Infrastructure.csproj
  Backend/src/Modules/Nodes/Nodes.Api/Extensions/ServiceCollectionExtensions.cs
  Backend/src/Modules/Nodes/Nodes.Api/GlobalUsing.cs
  Backend/src/Modules/Notes/Notes.Api/Extensions/ServiceCollectionExtensions.cs
  Backend/src/Modules/Notes/Notes.Api/Notes.Api.csproj
  Backend/src/Modules/Notes/Notes.Application/Notes.Application.csproj
  Backend/src/Modules/Notes/Notes.Domain/Notes.Domain.csproj
  Backend/src/Modules/Notes/Notes.Infrastructure/Notes.Infrastructure.csproj
  Backend/src/Modules/Reminders/Reminders.Api/Extensions/ServiceCollectionExtensions.cs
  Backend/src/Modules/Reminders/Reminders.Api/Reminders.Api.csproj
  Backend/src/Modules/Reminders/Reminders.Application/Reminders.Application.csproj
  Backend/src/Modules/Reminders/Reminders.Domain/Reminders.Domain.csproj
  Backend/src/Modules/Reminders/Reminders.Infrastructure/Reminders.Infrastructure.csproj
  Backend/src/Modules/Timelines/Timelines.Api/Extensions/ServiceCollectionExtensions.cs
  Backend/src/Modules/Timelines/Timelines.Api/Timelines.Api.csproj
  Backend/src/Modules/Timelines/Timelines.Application/Timelines.Application.csproj
  Backend/src/Modules/Timelines/Timelines.Domain/Timelines.Domain.csproj
  Backend/src/Modules/Timelines/Timelines.Infrastructure/Timelines.Infrastructure.csproj
  Backend/src/Timelines.sln
  README.md
Labels: enhancement

#8 Create Node Entity
  Backend/src/BuildingBlocks/BuildingBlocks.Domain/BuildingBlocks.Domain.csproj
  Backend/src/BuildingBlocks/BuildingBlocks.Domain/Entity.cs
  Backend/src/BuildingBlocks/BuildingBlocks.Domain/Exceptions/DomainException.cs
  Backend/src/BuildingBlocks/BuildingBlocks.Domain/IEntity.cs
  Backend/src/Modules/Nodes/Nodes.Domain/Models/Node.cs
  Backend/src/Modules/Nodes/Nodes.Domain/Nodes.Domain.csproj
  Backend/src/Modules/Nodes/Nodes.Domain/ValueObjects/Ids/NodeId.cs
  Backend/src/Timelines.sln
Labels: enhancement

#15 Implement Create Reminder Functionality
  Backend/src/Applications/Core/Core.Api/Extensions/DatabaseExtensions.cs
  Backend/src/Applications/Core/Core.Api/Extensions/ModuleExtensions.cs
  Backend/src/Applications/Core/Core.Api/Program.cs
  Backend/src/BuildingBlocks/BuildingBlocks.Domain/ValueObjects/Ids/ReminderId.cs
  Backend/src/Modules/Nodes/Nodes.Api/Extensions/ServiceCollectionExtensions.cs
  Backend/src/Modules/Nodes/Nodes.Domain/Models/Phase.cs
  Backend/src/Modules/Nodes/Nodes.Domain/NodesDomainTestClass.cs
  Backend/src/Modules/Reminders/Reminders.Api/Endpoints/CreateReminder.cs
  Backend/src/Modules/Reminders/Reminders.Api/Extensions/ServiceCollectionExtensions.cs
  Backend/src/Modules/Reminders/Reminders.Api/Reminders.Api.csproj
  Backend/src/Modules/Reminders/Reminders.Application/Data/IRemindersDbContext.cs
  Backend/src/Modules/Reminders/Reminders.Application/Dtos/ReminderDto.cs
  Backend/src/Modules/Reminders/Reminders.Application/Extensions/ServiceCollectionExtensions.cs
  Backend/src/Modules/Reminders/Reminders.Application/GlobalUsing.cs
  Backend/src/Modules/Reminders/Reminders.Application/Reminders.Application.csproj
  Backend/src/Modules/Reminders/Reminders.Application/Reminders/Commands/CreateReminder/CreateReminderCommand.cs
  Backend/src/Modules/Reminders/Reminders.Application/Reminders/Commands/CreateReminder/CreateReminderHandler.cs
  Backend/src/Modules/Reminders/Reminders.Domain/Events/ReminderCreatedEvent.cs
  Backend/src/Modules/Reminders/Reminders.Domain/Events/ReminderUpdatedEvent.cs
  Backend/src/Modules/Reminders/Reminders.Domain/GlobalUsing.cs
  Backend/src/Modules/Reminders/Reminders.Domain/Models/Reminder.cs
  Backend/src/Modules/Reminders/Reminders.Infrastructure/Data/Configurations/ReminderConfiguration.cs
  Backend/src/Modules/Reminders/Reminders.Infrastructure/Data/Extensions/DatabaseExtensions.cs
  Backend/src/Modules/Reminders/Reminders.Infrastructure/Data/Extensions/InitialData.cs
  Backend/src/Modules/Reminders/Reminders.Infrastructure/Data/Migrations/20241225150938_RemindersInit.Designer.cs
  Backend/src/Modules/Reminders/Reminders.Infrastructure/Data/Migrations/20241225150938_RemindersInit.cs
  Backend/src/Modules/Reminders/Reminders.Infrastructure/Data/Migrations/RemindersDbContextModelSnapshot.cs
  Backend/src/Modules/Reminders/Reminders.Infrastructure/Data/RemindersDbContext.cs
  Backend/src/Modules/Reminders/Reminders.Infrastructure/DependencyInjection.cs
  Backend/src/Modules/Reminders/Reminders.Infrastructure/GlobalUsing.cs
  Backend/src/Modules/Reminders/Reminders.Infrastructure/Reminders.Infrastructure.csproj
Labels: enhancement

#18 Implement Create File Functionality
  Backend/src/Applications/Core/Core.Api/Extensions/DatabaseExtensions.cs
  Backend/src/Applications/Core/Core.Api/Extensions/ModuleExtensions.cs
  Backend/src/BuildingBlocks/BuildingBlocks.Domain/ValueObjects/Ids/FileAssetId.cs
  Backend/src/Modules/Files/Files.Api/Endpoints/CreateFileAsset.cs
  Backend/src/Modules/Files/Files.Api/Extensions/ServiceCollectionExtensions.cs
  Backend/src/Modules/Files/Files.Api/Files.Api.csproj
  Backend/src/Modules/Files/Files.Application/Data/IFilesDbContext.cs
  Backend/src/Modules/Files/Files.Application/Dtos/FileAssetDto.cs
  Backend/src/Modules/Files/Files.Application/Extensions/ServiceCollectionExtensions.cs
  Backend/src/Modules/Files/Files.Application/Files.Application.csproj
  Backend/src/Modules/Files/Files.Application/Files/Commands/CreateFileAsset/CreateFileAssetCommand.cs
  Backend/src/Modules/Files/Files.Application/Files/Commands/CreateFileAsset/CreateFileAssetHandler.cs
  Backend/src/Modules/Files/Files.Application/GlobalUsing.cs
  Backend/src/Modules/Files/Files.Domain/Events/FileAssetCreatedEvent.cs
  Backend/src/Modules/Files/Files.Domain/Events/FileAssetUpdatedEvent.cs
  Backend/src/Modules/Files/Files.Domain/GlobalUsing.cs
  Backend/src/Modules/Files/Files.Domain/Models/FileAsset.cs
  Backend/src/Modules/Files/Files.Infrastructure/Data/Configurations/FileAssetConfiguration.cs
  Backend/src/Modules/Files/Files.Infrastructure/Data/Extensions/DatabaseExtensions.cs
  Backend/src/Modules/Files/Files.Infrastructure/Data/Extensions/InitialData.cs
  Backend/src/Modules/Files/Files.Infrastructure/Data/FilesDbContext.cs
  Backend/src/Modules/Files/Files.Infrastructure/Data/Migrations/20241226091110_FilesInit.Designer.cs
  Backend/src/Modules/Files/Files.Infrastructure/Data/Migrations/20241226091110_FilesInit.cs
  Backend/src/Modules/Files/Files.Infrastructure/Data/Migrations/FilesDbContextModelSnapshot.cs
  Backend/src/Modules/Files/Files.Infrastructure/DependencyInjection.cs
  Backend/src/Modules/Files/Files.Infrastructure/Files.Infrastructure.csproj
  Backend/src/Modules/Files/Files.Infrastructure/GlobalUsing.cs
  Backend/src/Modules/Reminders/Reminders.Application/Dtos/ReminderDto.cs
Labels: enhancement

#16 Implement Create Note Functionality
  .gitignore
  Backend/src/Applications/Core/Core.Api/Core.Api.csproj
  Backend/src/Applications/Core/Core.Api/Extensions/DatabaseExtensions.cs
  Backend/src/Applications/Core/Core.Api/Extensions/ModuleExtensions.cs
  Backend/src/BuildingBlocks/BuildingBlocks.Domain/ValueObjects/Ids/NoteId.cs
  Backend/src/Modules/Notes/Notes.Api/Endpoints/CreateNote.cs
  Backend/src/Modules/Notes/Notes.Api/Extensions/ServiceCollectionExtensions.cs
  Backend/src/Modules/Notes/Notes.Api/Notes.Api.csproj
  Backend/src/Modules/Notes/Notes.Application/Data/INotesDbContext.cs
  Backend/src/Modules/Notes/Notes.Application/Dtos/NoteDto.cs
  Backend/src/Modules/Notes/Notes.Application/Extensions/ServiceCollectionExtensions.cs
  Backend/src/Modules/Notes/Notes.Application/GlobalUsing.cs
  Backend/src/Modules/Notes/Notes.Application/Notes.Application.csproj
  Backend/src/Modules/Notes/Notes.Application/Notes/Commands/CreateNote/CreateNoteCommand.cs
  Backend/src/Modules/Notes/Notes.Application/Notes/Commands/CreateNote/CreateNoteHandler.cs
  Backend/src/Modules/Notes/Notes.Domain/Events/NoteCreatedEvent.cs
  Backend/src/Modules/Notes/Notes.Domain/Events/NoteUpdatedEvent.cs
  Backend/src/Modules/Notes/Notes.Domain/GlobalUsing.cs
  Backend/src/Modules/Notes/Notes.Domain/Models/Note.cs
  Backend/src/Modules/Notes/Notes.Infrastructure/Data/Configuration/NoteConfiguration.cs
  Backend/src/Modules/Notes/Notes.Infrastructure/Data/Extensions/DatabaseExtensions.cs
  Backend/src/Modules/Notes/Notes.Infrastructure/Data/Extensions/InitialData.cs
  Backend/src/Modules/Notes/Notes.Infrastructure/Data/Migrations/20241227111838_NotesInit.Designer.cs
  Backend/src/Modules/Notes/Notes.Infrastructure/Data/Migrations/20241227111838_NotesInit.cs
  Backend/src/Modules/Notes/Notes.Infrastructure/Data/Migrations/NotesDbContextModelSnapshot.cs
  Backend/src/Modules/Notes/Notes.Infrastructure/Data/NotesDbContext.cs
  Backend/src/Modules/Notes/Notes.Infrastructure/DependencyInjection.cs
  Backend/src/Modules/Notes/Notes.Infrastructure/GlobalUsing.cs
  Backend/src/Modules/Notes/Notes.Infrastructure/Notes.Infrastructure.csproj
  Backend/src/Timelines.sln
  Docs/.obsidian/workspace.json
  Docs/Migrations.md
Labels: enhancement

#24 Add Swagger Documentation to the Solution
  Backend/src/Applications/Core/Core.Api/Core.Api.csproj
  Backend/src/Applications/Core/Core.Api/Extensions/ApplicationBuilderExtensions.cs
  Backend/src/Applications/Core/Core.Api/Extensions/ServiceCollectionExtensions.cs
  Backend/src/Applications/Core/Core.Api/Program.cs
Labels: documentation

#26 Add React Frontend Project
  Frontend/react-app/.gitignore
  Frontend/react-app/README.md
  Frontend/react-app/package-lock.json
  Frontend/react-app/package.json
  Frontend/react-app/public/favicon.ico
  Frontend/react-app/public/index.html
  Frontend/react-app/public/logo192.png
  Frontend/react-app/public/logo512.png
  Frontend/react-app/public/manifest.json
  Frontend/react-app/public/robots.txt
  Frontend/react-app/src/App.jsx
  Frontend/react-app/src/App.test.js
  Frontend/react-app/src/assets/images/logo.svg
  Frontend/react-app/src/components/Timeline/Timeline.css
  Frontend/react-app/src/components/Timeline/Timeline.jsx
  Frontend/react-app/src/components/TimelineCard/TimelineCard.css
  Frontend/react-app/src/components/TimelineCard/TimelineCard.jsx
  Frontend/react-app/src/data/timelineData.js
  Frontend/react-app/src/index.css
  Frontend/react-app/src/index.js
  Frontend/react-app/src/styles/App.css
Labels: enhancement, frontend

#28 Implement label validation during the creation of new pull requests
  .github/workflows/check-pr.yml
Labels: enhancement

#29 Address Issues After the Notes PR Was Merged
  Backend/src/Applications/Core/Core.Api/Core.Api.csproj
  Backend/src/Applications/Core/Core.Api/Extensions/DatabaseExtensions.cs
  Backend/src/Applications/Core/Core.Api/Program.cs
  Backend/src/BuildingBlocks/BuildingBlocks.Api/BuildingBlocks.Api.csproj
  Backend/src/BuildingBlocks/BuildingBlocks.Api/Converters/NodeIdConverter.cs
  Backend/src/BuildingBlocks/BuildingBlocks.Api/GlobalUsing.cs
  Backend/src/BuildingBlocks/BuildingBlocks.Application/BuildingBlocks.Application.csproj
  Backend/src/BuildingBlocks/BuildingBlocks.Domain/GlobalUsing.cs
  Backend/src/BuildingBlocks/BuildingBlocks.Domain/ValueObjects/Ids/FileAssetId.cs
  Backend/src/BuildingBlocks/BuildingBlocks.Domain/ValueObjects/Ids/NodeId.cs
  Backend/src/BuildingBlocks/BuildingBlocks.Domain/ValueObjects/Ids/NoteId.cs
  Backend/src/Modules/Files/Files.Api/Files.Api.csproj
  Backend/src/Modules/Files/Files.Infrastructure/Data/Extensions/InitialData.cs
  Backend/src/Modules/Nodes/Nodes.Api/Endpoints/Nodes/GetNodeById.cs
  Backend/src/Modules/Nodes/Nodes.Api/Extensions/ServiceCollectionExtensions.cs
  Backend/src/Modules/Nodes/Nodes.Api/Nodes.Api.csproj
  Backend/src/Modules/Notes/Notes.Api/Notes.Api.csproj
  Backend/src/Modules/Notes/Notes.Infrastructure/Data/Extensions/InitialData.cs
  Backend/src/Modules/Reminders/Reminders.Api/Reminders.Api.csproj
  Backend/src/Modules/Reminders/Reminders.Infrastructure/Data/Extensions/InitialData.cs
  Backend/src/Modules/Timelines/Timelines.Api/Timelines.Api.csproj
Labels: bug, backend

#22 Implement Create Timeline Functionality
  Backend/src/Applications/Core/Core.Api/Extensions/DatabaseExtensions.cs
  Backend/src/Applications/Core/Core.Api/Extensions/ModuleExtensions.cs
  Backend/src/BuildingBlocks/BuildingBlocks.Domain/ValueObjects/Ids/TimelineId.cs
  Backend/src/Modules/Timelines/Timelines.Api/Endpoints/CreateTimeline.cs
  Backend/src/Modules/Timelines/Timelines.Api/Extensions/ServiceCollectionExtensions.cs
  Backend/src/Modules/Timelines/Timelines.Application/Data/ITimelinesDbContext.cs
  Backend/src/Modules/Timelines/Timelines.Application/Dtos/TimelineDto.cs
  Backend/src/Modules/Timelines/Timelines.Application/Extensions/ServiceCollectionExtensions.cs
  Backend/src/Modules/Timelines/Timelines.Application/GlobalUsing.cs
  Backend/src/Modules/Timelines/Timelines.Application/Timelines.Application.csproj
  Backend/src/Modules/Timelines/Timelines.Application/Timelines/Commands/CreateTimeline/CreateTimelineCommand.cs
  Backend/src/Modules/Timelines/Timelines.Application/Timelines/Commands/CreateTimeline/CreateTimelineHandler.cs
  Backend/src/Modules/Timelines/Timelines.Domain/Events/TimelineCreatedEvent.cs
  Backend/src/Modules/Timelines/Timelines.Domain/Events/TimelineUpdatedEvent.cs
  Backend/src/Modules/Timelines/Timelines.Domain/GlobalUsing.cs
  Backend/src/Modules/Timelines/Timelines.Domain/Models/Timeline.cs
  Backend/src/Modules/Timelines/Timelines.Infrastructure/Data/Configurations/TimelineConfiguration.cs
  Backend/src/Modules/Timelines/Timelines.Infrastructure/Data/Extensions/DatabaseExtensions.cs
  Backend/src/Modules/Timelines/Timelines.Infrastructure/Data/Extensions/InitialData.cs
  Backend/src/Modules/Timelines/Timelines.Infrastructure/Data/Migrations/20241227122955_TimelinesInit.Designer.cs
  Backend/src/Modules/Timelines/Timelines.Infrastructure/Data/Migrations/20241227122955_TimelinesInit.cs
  Backend/src/Modules/Timelines/Timelines.Infrastructure/Data/Migrations/TimelinesDbContextModelSnapshot.cs
  Backend/src/Modules/Timelines/Timelines.Infrastructure/Data/TimelinesDbContext.cs
  Backend/src/Modules/Timelines/Timelines.Infrastructure/DependencyInjection.cs
  Backend/src/Modules/Timelines/Timelines.Infrastructure/GlobalUsing.cs
  Backend/src/Modules/Timelines/Timelines.Infrastructure/Timelines.Infrastructure.csproj
Labels: enhancement, backend

#33 Implement Strongly Typed Ids
  Backend/src/BuildingBlocks/BuildingBlocks.Domain/GlobalUsing.cs
  Backend/src/BuildingBlocks/BuildingBlocks.Domain/ValueObjects/Ids/FileAssetId.cs
  Backend/src/BuildingBlocks/BuildingBlocks.Domain/ValueObjects/Ids/NodeId.cs
  Backend/src/BuildingBlocks/BuildingBlocks.Domain/ValueObjects/Ids/NoteId.cs
  Backend/src/BuildingBlocks/BuildingBlocks.Domain/ValueObjects/Ids/ReminderId.cs
  Backend/src/BuildingBlocks/BuildingBlocks.Domain/ValueObjects/Ids/TimelineId.cs
  Backend/src/BuildingBlocks/BuildingBlocks.Domain/ValueObjects/StronglyTypedId.cs
  Backend/src/Modules/Files/Files.Api/Endpoints/CreateFileAsset.cs
  Backend/src/Modules/Files/Files.Api/GlobalUsing.cs
  Backend/src/Modules/Files/Files.Application/Files/Commands/CreateFileAsset/CreateFileAssetCommand.cs
  Backend/src/Modules/Files/Files.Domain/Models/FileAsset.cs
  Backend/src/Modules/Nodes/Nodes.Domain/ValueObjects/Ids/PhaseId.cs
Labels: enhancement, backend
